import { useDataContext } from "dataContext";
import { type NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import DogCard from "~/components/DogCard";
import Header from "~/components/Header";
import { type Dog } from "~/server/api/models/dogs";

const DogMatchPage: NextPage = () => {
  const { data } = useDataContext();
  const [matchDog, setMatchDog] = useState({} as Dog);

  useEffect(() => {
    if (data) {
      setMatchDog(data);
    }
  }, [data]);

  return (
    <>
      <Head>
        <title>PawfectPals App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <h1 className="mt-4 font-bold text-white">
          You have been matched with {`${matchDog.name}`}
        </h1>
        <div className="mt-4">
          <DogCard dog={matchDog} />
        </div>
      </main>
    </>
  );
};

export default DogMatchPage;
