import { type NextPage } from "next";
import Head from "next/head";
import Header from "~/components/Header";
import MatchedResult from "~/components/MatchedResult";

const DogMatchPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>T3 Dogs App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <h1 className="text-white">
          {" "}
          this the page where the matchDog and with dog component will be
          rendered
        </h1>
      </main>
    </>
  );
};

export default DogMatchPage;
