/* eslint-disable @typescript-eslint/no-unsafe-call */
import axios from "axios";
import { type NextPage } from "next";
import { cookies } from "next/dist/client/components/headers";
import { NextRouter, useRouter } from "next/dist/client/router";
import Head from "next/head";
import { useCallback, useEffect } from "react";
import DogResults from "~/components/DogResults";
import Header from "~/components/Header";
import Search from "~/components/Search";

export type ReplaceRouterWith =
  | NextRouter
  | {
      pathname?: string;
      query?: unknown;
    };

const DogsPage: NextPage = () => {
  const router = useRouter();
  const { query } = router;

  const updateRouter = () => {
    console.log({ router });
    router.replace("/dogs/search", undefined, { scroll: false });
  };
  // const getUrl = () => {
  //   void axios({
  //     method: "GET",
  //     url: `https://frontend-take-home-service.fetch.com/dogs/search`,
  //   }).then(({ data }) => {
  //     console.log(data);
  //   });
  // };

  useEffect(() => {
    // getUrl();
    updateRouter();
  }, []);
  return (
    <>
      <Head>
        <title>T3 Dogs App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <Search />
        <DogResults />
      </main>
    </>
  );
};

export default DogsPage;
