// interface DogsProps {}

import Head from "next/head";
import DogResults from "~/components/DogResults";
import Header from "~/components/Header";
import Search from "~/components/Search";

const Dogs: React.FC = () => {
  return (
    <>
      <Head>
        <title>T3 Dogs App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <Search />
        <DogResults />
      </main>
    </>
  );
};

export default Dogs;
