/* eslint-disable @typescript-eslint/no-unsafe-assignment */
import Head from "next/head";
// import { api } from "~/utils/api";
import LoginForm from "~/components/LoginForm";

export default function Home() {
  return (
    <>
      <Head>
        <title>T3 Dogs App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <LoginForm />
      </main>
    </>
  );
}
