import { type NextPage } from "next";
import Head from "next/head";
import LoginForm from "~/components/LoginForm";

const LoginPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Fetch Dogs App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <LoginForm />
      </main>
    </>
  );
};

export default LoginPage;
