import { type NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import DogResults from "~/components/DogResults";
import Header from "~/components/Header";
import Search from "~/components/Search";
import { type Dog } from "~/server/api/models/dogs";
import { api } from "~/utils/api";

const DogsPage: NextPage = () => {
  const [selectedFilters, setSelectedFilters] = useState([] as string[]);

  const getDogBreeds = api.dogs.breeds.useQuery()?.data?.breed as string[];

  const searchDogs = api.dogs.searchDogs.useQuery({
    breeds: [],
  }).data?.dogObj as unknown as Dog[];

  const clearSelectedFilters = () => {
    setSelectedFilters([]);
  };

  console.log({ selectedFilters });
  return (
    <>
      <Head>
        <title>T3 Dogs App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <Search
          selectedFilters={selectedFilters}
          setSelectedFilters={setSelectedFilters}
          getDogBreeds={getDogBreeds}
          clearSelectedFilters={clearSelectedFilters}
        />
        <DogResults searchDogs={searchDogs} />
      </main>
    </>
  );
};

export default DogsPage;
