import { type NextPage } from "next";
import { useRouter } from "next/dist/client/router";
import Head from "next/head";
import { useMemo } from "react";
import DogResults from "~/components/DogResults";
import Header from "~/components/Header";
import Search from "~/components/Search";
import { useSearchParams } from "next/navigation";

const DogsPage: NextPage = () => {
  const router = useRouter();

  const searchParams = useSearchParams();

  const current = useMemo(
    () => new URLSearchParams(searchParams.toString()),
    [searchParams]
  );
  const getparams = searchParams.get("breeds") ?? "";

  const selectedFilters = getparams
    .split("_")
    .filter((val: string) => val != "");

  const clearSelectedFilters = () => {
    current.delete("breeds");
    const deletedBreeds = `${router.pathname}?${current.toString()}`;
    void router.push(deletedBreeds, undefined, { shallow: true });
  };

  const onHandleChange = (selectedFilters: string[]) => {
    current.set("breeds", selectedFilters.join("_"));
    const newUrl = `${router.pathname}?${current.toString()}`;
    void router.push(newUrl, undefined, { shallow: true });
  };

  return (
    <>
      <Head>
        <title>T3 Dogs App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <Search
          selectedFilters={selectedFilters}
          onHandleChange={onHandleChange}
          clearSelectedFilters={clearSelectedFilters}
        />
        <DogResults selectedFilters={selectedFilters} />
      </main>
    </>
  );
};

export default DogsPage;
